### ISSUE TITLE
Problem with memory consumption - memory leak

### ISSUE THREAD

**Issue by lrydzkowski** [CrystallizeAPI/import-utilities#91]
Hi, we're using import-utilities library in our project responsible for transferring data from the external ERP system to Crystallize. Over the past month we noticed a steady increase in the memory consumption of this project. After the investigation I came to a conclusion that the most probable culprit is import-utilities library.
In order to confirm that I've created an isolated application in Node.js that uses import-utilities library for updating stock in Crystallize:

https://github.com/lrydzkowski/crystallize-import-utilities-example

This projects allows you to carry out the series of tests with the following operations:

1. Run a request responsible for creating an initial memory dump.
2. Wait 2 seconds.
3. Run the iteration of tests 10 times. Each iteration contains the following operations:
    1. Send 10 requests to an endpoint responsible for updating a product in Crystallize by import-utilities library.
    2. Wait 30 seconds.
    3. Send a request responsible for running garbage collection.
    4. Wait 2 seconds.
    5. Send a request responsible for creating a memory dump.
4. In the end there should be 11 memory dumps in `memory-dump` directory in the main directory of this project.
5. You can analyze and compare individual memory dumps in Chrome developer tools.

Here you can see how the size of each memory dump is higher then previous once:

![image](https://github.com/CrystallizeAPI/import-utilities/assets/1909426/d5a189eb-53ad-45df-8659-d36d0dcf5338)

To compare I also run the same thing but with @crystallize/js-api-client library instead of @crystallize/import-utilities:

![image](https://github.com/CrystallizeAPI/import-utilities/assets/1909426/6339442d-894c-413f-88f0-43dea8766711)

After a few iterations memory consumption doesn't increase.

I also run the same thing with an empty endpoint without any operations inside:

![image](https://github.com/CrystallizeAPI/import-utilities/assets/1909426/2833af5c-d74d-4db7-939b-212acfd23d01)

After a few iterations memory consumption doesn't increase.

Tools that I used:

- Node.js 18
- @crystallize/import-utilities@1.28.0

**Comment by Plopix** [comment]
so I was able to reduce that leak by calling `.kill`
it's not perfect but much much better 

![Screenshot 2023-08-31 at 10 52 41 AM](https://github.com/CrystallizeAPI/import-utilities/assets/313532/54442646-ef2f-4a83-9df8-cee4d067b509)
